apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-halo-ai-console-view-and-manage-own
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/module: "Halo AI Console"
    rbac.authorization.halo.run/display-name: "Halo AI"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:halo-ai-console:view","plugin:halo-ai-console:manage-own"]
rules:
  - apiGroups: ["console.api.aifoundation.halo.run"]
    resources: ["model-options", "models", "models/*"]
    verbs: ["get", "list", "create"]
  - apiGroups: ["console.api.halo-ai-console.halo.run"]
    resources:
      ["sessions-with-messages", "sessions", "call-logs", "settings",
       "assets/dompurify.min.js", "image-caches", "attachments/upload", "jobs", "jobs/*", "jobs/chat", "jobs/image", "jobs/cancel"]
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups: ["console.api.halo-ai-console.halo.run"]
    resources: ["global-settings"]
    verbs: ["get", "list"]
  - apiGroups: ["console.api.storage.halo.run"]
    resources: ["attachments"]
    verbs: ["create"]
---
apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-halo-ai-console-audit
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/dependencies: |
      ["role-template-halo-ai-console-view-and-manage-own"]
    rbac.authorization.halo.run/module: "Halo AI Console"
    rbac.authorization.halo.run/display-name: "View own AI audit logs"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:halo-ai-console:audit"]
rules:
  - apiGroups: ["console.api.halo-ai-console.halo.run"]
    resources: ["audit-logs"]
    verbs: ["get", "list"]
---
apiVersion: v1alpha1
kind: Role
metadata:
  name: role-template-halo-ai-console-admin
  labels:
    halo.run/role-template: "true"
  annotations:
    rbac.authorization.halo.run/dependencies: |
      ["role-template-halo-ai-console-view-and-manage-own"]
    rbac.authorization.halo.run/module: "Halo AI Console"
    rbac.authorization.halo.run/display-name: "Manage Halo AI Console"
    rbac.authorization.halo.run/ui-permissions: |
      ["plugin:halo-ai-console:admin","plugin:halo-ai-console:call-log-all"]
rules:
  - apiGroups: ["console.api.halo-ai-console.halo.run"]
    resources:
      ["call-logs/all", "audit-logs/all", "migration/legacy", "migration/legacy/status", "global-settings"]
    verbs: ["get", "list", "create", "update", "delete"]
